### ISSUE TITLE
Mention Responser

### ISSUE THREAD

**Issue by Riensjard** [b3r3nd/berendbotje#33]
1: Instead of hardcoding the responses (per role), make it a command e.g. /addresponse (role or user ID) (response line). Also a method to view the roles e.g. /responselist (role). If this list is opened every response should have like its own tag so it is easy to remove by /removeresponse (response ID).
2: More diversity in responses e.g. province or game
3: Instead of using $counter > x, use top x from counter list like muted or bumpers

**Comment by b3r3nd** [comment]
👍

**Comment by b3r3nd** [comment]
- Ability to create categories yourself based on role in the server, for example Strijder, Weeb, NSFW, etc.
- Ability to create categories for single users (provide user ID).
- Ability to add responses to hardcoded categories, these categories cannot be removed, for example high amount of cringe, a lot of bumps or a certain amount of timeouts.

Commands:

- `responses` - show all replies grouped by available categories
- `responses` `group_identifier` - show all replies for a single group
- `addgroup` `group_identifier` - add a group (user ID or role ID)
- `delgroup` `group_identifier` - Delete a group (ID of the group)
- `addreply` `group_identifier` `response_line` - Add a reply to a group
- `delreply` `group_identifier` `reply_identifier` 
- `searchreply` `search_term` - search for a reply 

That is how I think it should work, not including adding a weight system to replies.

**Comment by b3r3nd** [comment]
MentionReply - mention_replies
MentionGroup  - mentions_groups

- Load mentions in Guild class ONCE, only re-read from database when replies are added or removed
- Add 2 permissions, add reply and del reply
- Add current default settings to seeder for guild 2 (netherlands)

**Comment by b3r3nd** [comment]
Implement a way to give replies when a role is NOT detected
